runtime: nodejs14 # or python39 or whatever your runtime is

automatic_scaling:
  target_cpu_utilization: 0.65

instance_class: F2

handlers:
- url: /styles
  static_dir: styles

- url: /.*
  script: auto
